---
resources:
- name: concourse-tutorial
  type: git
  source:
    uri: https://github.com/Hemashree3016/concourse-tutorial.git
    branch: develop
- name: concourse-gist
  type: git
  source:
    branch: master
    uri:         ((publishing-outputs-gist-uri))
    private_key: ((publishing-outputs-private-key))

jobs:
- name: job-bump-date
  serial: true
  plan:
  - get: concourse-tutorial
  - get: resource-gist
  - task: bump-timestamp-file
    config:
      platform: linux
      image_resource:
        type: resigtry-image
        source: { repository: arm64v8/starkandwayne/concourse }
      inputs:
        - name: concourse-tutorial
        - name: resource-gist
      outputs:
        - name: updated-gist
      run:
        path: concourse-tutorial/tutorials/basic/publishing-outputs/bump-timestamp-file.sh
  - put: concourse-gist
    params: {repository: arm64v8/updated-gist}

- name: job-show-date
  plan:
  - get: concourse-tutorial
  - get: concourse-gist
    passed: [job-bump-date]
    trigger: true
  - task: show-date
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: arm64v8/busybox}
      inputs:
        - name: concourse-gist
      run:
        path: cat
        args: [concourse-gist/bumpme]
