---
resources:
- name: concourse-tutorial
  type: git
  source:
    uri: https://github.com/Hemashree3016/concourse-tutorial.git
    branch: develop

jobs:
- name: job-pass-files
  public: true
  plan:
  - get: concourse-tutorial
  - task: create-some-files
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: arm64v8/busybox}

      inputs:
      - name: concourse-tutorial
      outputs:
      - name: some-files

      run:
        path: concourse-tutorial/tutorials/basic/task-outputs-to-inputs/create_some_files.sh

  - task: show-some-files
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: arm64v8/busybox}

      inputs:
      - name: concourse-tutorial
      - name: some-files

      run:
        path: concourse-tutorial/tutorials/basic/task-outputs-to-inputs/show_files.sh

